### ISSUE TITLE
Change wording on banner panels from singular to plural as resource count changes

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#43]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

Should the following banner panels have text that switches from singular to plural as we get above a count of 1 resource?

![Screen Shot 2020-03-28 at 11 35 00 PM](https://user-images.githubusercontent.com/58799043/77839700-f7f98700-714c-11ea-94dc-d125787ec896.png)

![Screen Shot 2020-03-28 at 11 34 23 PM](https://user-images.githubusercontent.com/58799043/77839701-f7f98700-714c-11ea-8bb5-90812549a022.png)

![Screen Shot 2020-03-28 at 11 31 07 PM](https://user-images.githubusercontent.com/58799043/77839702-f8921d80-714c-11ea-8079-3ff4a049f702.png)

**Comment by suddengenesis** [comment]
Which ones make sense to have different singular/plural phrases? Here are the set I'm pretty sure should:

- Free grocery location(s)
- Free meal location(s)
- Free produce location(s)
- Medical worker discount(s)

These I'm not sure about but am leaning toward probably:

- Meal(s) for students
- Meal(s) open to public

These don't look like they need to be plural:

- Curbside pick-up
- Delivery
- Order & pay online
- Senior shopping hours

**Comment by suddengenesis** [comment]
I notice that in Spanish "Curbside pick-up" is translated to "Restaurantes con recogida en la acera" and in French as "Restaurants avec ramassage en bordure de rue" which sound like they should aware of the number. I don't know Korean to tell if that one has any others that may also need the same treatment.

**Comment by readingdancer** [comment]
There is the ability to use singular and plural in the translation files, instead of using $t you need to use $tc like this:

`this.$tc('category.restaurant', 2)`

The number indicates the number of items.

The two translations are stored with a pipe between them, e.g.

`"restaurant": "Restaurant|Restaurants",`

**Comment by KM-Hanson** [comment]
@suddengenesis 

**Adding one more item from Issue #46:**

Farmers market(s)

**Agree with:**

Free grocery location(s)
Free meal location(s)
Free produce location(s)
Medical worker discount(s)

I think we should leave both "free meals" items as fixed plural.

**Comment by suddengenesis** [comment]
I've also noticed that "Curbside Pick-up" is used each of grocery, restaurant, pharmacy, and pet, as well as the currently unused "family" category. It would probably be more appropriate to translate this as "business" rather than "restaurant" in Spanish and French. I recommend we open a separate translation issue on that, but will handle the plural for it with this change.
