### ISSUE TITLE
Add summary banner for "Prepared Family Meals" resources

### ISSUE THREAD

**Issue by KM-Hanson** [code-for-chapel-hill/COVID-Support-For-CH#48]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.

We need the following 4 summary banner panels to accompany the "Prepared Family Meals" resources:

Order & pay online
Delivery
Curbside pick-up
Pre-order

**Comment by KM-Hanson** [comment]
@amkitt We will also need to add a column to the database that codes 0/1 for pre-order

**Comment by readingdancer** [comment]
@KM-Hanson With the current flat data structure, this is not possible. The current drop down filter selects records based on the Resource column, i.e. if you select "Restaurant" it will return all the restaurants.

I was envisaging these prepared meals would all be coming from that category? I.e. rather than add another category to the drop down, could we not have one of the top filters ( or an additional filter on the left ) to then only show those offering the family meals?

What do you think?

**Comment by KM-Hanson** [comment]
@readingdancer This is related to #47 (which asks to create a drop-down item for "Prepared Family Meals."

I wanted to add a "pre-order" panel to the banner because many of the family meal operations are only offered certain days of the week and you have to place a pre-order a day or a few days before picking up the food. I think it is easier for the user to have the "Prepared Family Meals" as a separate drop-down item (and we can create a new category for it in the 'resource' column of the database). My feelings on this are similar to the motivation to create a separate drop-down item for "Farms & Farmers Markets". Both are ways of getting food that might not occur to a shopper off the top of their head, so I like having the drop-down item as a way to prompt users to think about these options. The instructions on how to order the prepared family meals are pretty tricky sometimes (limited and odd hours for ordering and pick-up). But as the restrictions accrue, more and more traditional restaurants are ending normal business hours and moving to a prepared family meal option, even though this is not something that they offered in the past. So customers don't really know to look for or ask for this option. Long story short- I vote for making a new category!

**Comment by readingdancer** [comment]
This has been implemented :)
